resources:
- name: koa-starter
  type: git
  source:
    uri: https://github.com/ineentho/koa-starter.git
    branch: master

jobs:
- name: build-koa-starter
  plan:
  - aggregate:
    - do:
      - get: koa-starter
        trigger: true
      - aggregate:
        - task: install-dev
          file: koa-starter/ci/install-dev.yml
  - aggregate:
    - task: lint
      file: koa-starter/ci/lint.yml
    - task: test
      file: koa-starter/ci/test.yml
